services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Pass the database connection string as an environment variable
      # Use the service name 'db' as the hostname to connect to the database service
      DATABASE_URL: postgres://user:password@db:5432/mydatabase?sslmode=disable
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
