// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"token-transfer-api/internal/address"
	"token-transfer-api/internal/decimal"
)

type Mutation struct {
}

type Query struct {
}

type Sender struct {
	Balance decimal.Decimal `json:"balance"`
}

type Transfer struct {
	FromAddress address.Address `json:"from_address"`
	ToAddress   address.Address `json:"to_address"`
	Amount      decimal.Decimal `json:"amount"`
}
