package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"log"
	"token-transfer-api/internal/graph/model"
)

// Transfer is the resolver for the transfer field.
func (r *mutationResolver) Transfer(ctx context.Context, input model.Transfer) (*model.Sender, error) {
	defer func() {
		r := recover()
		if r != nil {
			log.Println("Recovered in Transfer", r)
		}
	}()

	log.Printf("not implemented: Transfer - transfer")
	return nil, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
