name: Build

on:
  push:
    branches:
      - main
      - staging
      - develop
  pull_request:
    branches:
      - main
      - staging
      - develop
jobs:
  build-go-and-docker:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

      DATABASE_TEST_URL: ${{ secrets.DATABASE_TEST_URL }}
      POSTGRES_TEST_USER: ${{ secrets.POSTGRES_TEST_USER }}
      POSTGRES_TEST_PASSWORD: ${{ secrets.POSTGRES_TEST_PASSWORD }}
      POSTGRES_TEST_DB: ${{ secrets.POSTGRES_TEST_DB }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start test services
        run: docker compose up -d --wait test-db tester

      - name: Run tests
        run: docker compose exec tester go test -v ./...

      - name: Stop services
        if: always()
        run: docker compose down
