name: Build

on:
  push:
    branches:
      - exp/ci-cd
      - main
      - staging
      - develop
  pull_request:
    branches:
      - main
      - staging
      - develop
jobs:
  build-go-and-docker:
    runs-on: ubuntu-latest

    services:
      postgres_db:
        image: postgres:15
        ports:
          - 5432/tcp
        environment:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Download wait-for-it.sh
        run: |
          curl -o wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
          chmod +x wait-for-it.sh

      - name: Wait for PostgreSQL to be ready
        run: ./wait-for-it.sh localhost:5432 --timeout=60 --strict -- \
          echo "PostgreSQL is ready!"

      - name: Set Test Database URL
        run: echo "TEST_DATABASE_URL=postgres://test:test@localhost:5432/testdb?sslmode=disable" >> $GITHUB_ENV

      - name: Build Go application
        run: go build -v ./...

      - name: Run Go tests
        run: go test -v ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t token-transfer-api:latest .
