name: Build

on:
  push:
    branches:
      - exp/ci-cd
      - main
      - staging
      - develop
  pull_request:
    branches:
      - main
      - staging
      - develop
jobs:
  build-go-and-docker:
    runs-on: ubuntu-latest

    services:
      postgres_db:
        image: postgres:15
        ports:
          - 5432/tcp
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t token-transfer-api:latest .

      - name: Stop the app container
        run: docker compose stop app

      - name: Run Go tests in tester container
        run: docker compose run --rm tester go test -v ./tests/integration/...
        env:
          DATABASE_URL: "postgresql://test:test@db:5432/testdb?sslmode=disable"
