name: Build

on:
  push:
    branches:
      - main
      - staging
      - develop
  pull_request:
    branches:
      - main
      - staging
      - develop
jobs:
  build-go-and-docker:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "postgres://user:password@db:5432/mydatabase?sslmode=disable"
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase

      DATABASE_TEST_URL: "postgres://test_user:test_password@test-db:5432/token_transfer_test_db?sslmode=disable"
      POSTGRES_TEST_USER: test_user
      POSTGRES_TEST_PASSWORD: test_password
      POSTGRES_TEST_DB: token_transfer_test_db

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start test services
        run: docker compose up -d --wait test-db tester

      - name: Run tests
        run: docker compose exec tester go test -v ./...

      - name: Stop services
        if: always()
        run: docker compose down
